# Generated by Django 4.2.3 on 2023-09-24 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_alter_event_players'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusOne',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('value', models.SmallIntegerField()),
                ('event', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='plus_ones', to='games.event')
                 ),
                ('user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='plus_ones', to=settings.AUTH_USER_MODEL)
                 ),
            ],
        ),
    ]
