# Generated by Django 4.2.5 on 2023-12-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
