# Generated by Django 4.2.3 on 2023-09-24 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(
                blank=True, related_name='games',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
